spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: admin
  password: admin

camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: 8